// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUserInput struct {
	Username string  `json:"username"`
	FullName *string `json:"fullName,omitempty"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	FullName *string `json:"fullName,omitempty"`
	Email    string  `json:"email"`
}
